- name: add repositories
  yum: name={{item}}
  with_items:
    - http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

# disable nginx repo
- name: replace repo settings
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - nginx.repo

# nginx
- name: install nginx
  yum: name={{ item }} enablerepo=nginx state=present
  with_items:
    - nginx
- name: put virtual.conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  sudo: yes

# firewall
- name: add http to firewall
  command: firewall-cmd --permanent --add-service=http
- name: add https to firewall
  command: firewall-cmd --permanent --add-service=https
- name: reload firewall
  command: firewall-cmd --reload
